dat <- read.csv(unz("../data/202001_BolsaFamilia_Pagamentos_reduced.zip"), sep=";")
dat <- read.csv(unz("../data/202001_BolsaFamilia_Pagamentos_reduced.zip", "../data/202001_BolsaFamilia_Pagamentos_reduced.csv"), sep=";")
dat <- read.csv(unz("../data/202001_BolsaFamilia_Pagamentos_reduced.zip", "202001_BolsaFamilia_Pagamentos_reduced.csv"), sep=";")
head(dat)
library(brazilmaps)
uf_map <- get_brmap("State")
names(uf_map)
head(uf_map)
uf_map$State
ls()
head(dat)
as.numeric(dat$VALOR.PARCELA)
as.numeric(dat$VALOR.PARCELA)[1]
head(dat)
as.numeric(dat$VALOR.PARCELA, dec=",")[1]
dat$VALOR.PARCELA[1]
as.numeric(dat$VALOR.PARCELA[1])
as.numeric(dat$VALOR.PARCELA)
as.numeric(levels(dat$VALOR.PARCELA))
as.numeric(levels(dat$VALOR.PARCELA), dec=",")
as.numeric(levels(dat$VALOR.PARCELA[1]), dec=",")
as.numeric(levels(dat$VALOR.PARCELA[1]))
dat$VALOR.PARCELA[1])
dat$VALOR.PARCELA[1]
as.numeric(dat$VALOR.PARCELA[1])
as.character(dat$VALOR.PARCELA[1])
as.numeric(as.character(dat$VALOR.PARCELA))
as.numeric(as.character(dat$VALOR.PARCELA), dec=",")
as.numeric(as.character(dat$VALOR.PARCELA[1]), dec=",")
as.numeric(as.character(dat$VALOR.PARCELA[1]))
as.character(dat$VALOR.PARCELA[1])
dat$VALOR.PARCELA <- as.character(dat$VALOR.PARCELA)
head(dat)
glimpse(dat)
library(tidyverse)
glimpse(dat)
dat$VALOR.PARCELA <- as.numeric(sub(",", ".",dat$VALOR.PARCELA, fixed=TRUE))
head(dat$VALOR.PARCELA)
head(dat)
glimpse(dat)
dat %>% group_by(UF) %>% summarise(total = sum(VALOR.PARCELA))
dat %>% group_by(UF) %>% summarise(total = sum(VALOR.PARCELA)) %>% arrange(total) %>% tail(20)
dat %>% filter(MES.REFERENCIA == 202001) %>% group_by(UF) %>% summarise(total = sum(VALOR.PARCELA)) %>% arrange(total) %>% tail(20)
dat %>% filter(MES.COMPETENCIA == 201901) %>% group_by(UF) %>% summarise(total = sum(VALOR.PARCELA)) %>% arrange(total) %>% tail(20)
dat %>% filter(MES.COMPETENCIA == 201902) %>% group_by(UF) %>% summarise(total = sum(VALOR.PARCELA)) %>% arrange(total) %>% tail(20)
dat %>% filter(MES.COMPETENCIA == 201905) %>% group_by(UF) %>% summarise(total = sum(VALOR.PARCELA)) %>% arrange(total) %>% tail(20)
head(dat)
dat %%> group_by(CODIGO.MUNICIPIO.SIAFI) %>% summarise(total = sum(VALOR.PARCELA)) %>% arrange(total) %>% tail(20)
dat %>% group_by(CODIGO.MUNICIPIO.SIAFI) %>% summarise(total = sum(VALOR.PARCELA)) %>% arrange(total) %>% tail(20)
library(readxl)
siafi_ibge <- read_xlsx("../data/TABMUN-SIAFI.xlsx")
head(siafi_ibge)
dat %>% left_join(siafi_ibge %>% select(`CÓDIGO SIAFI`,`CÓDIGO IBGE`), by=c("CODIGO.MUNICIPIO.SIAFI" = `CÓDIGO SIAFI`)
dat %>% left_join(siafi_ibge %>% select(`CÓDIGO SIAFI`,`CÓDIGO IBGE`), by=c("CODIGO.MUNICIPIO.SIAFI" = `CÓDIGO SIAFI`))
dat %>% left_join(siafi_ibge, by=c("CODIGO.MUNICIPIO.SIAFI" = `CÓDIGO SIAFI`))
dat %>% left_join(siafi_ibge, by=c("CODIGO.MUNICIPIO.SIAFI" = "CÓDIGO SIAFI"))
siafi_ibge$`CÓDIGO SIAFI`
siafi_ibge$`CÓDIGO SIAFI` <- as.numeric(siafi_ibge$`CÓDIGO SIAFI`)
dat %>% left_join(siafi_ibge, by=c("CODIGO.MUNICIPIO.SIAFI" = "CÓDIGO SIAFI"))
dat_with_ibge <- dat %>% left_join(siafi_ibge, by=c("CODIGO.MUNICIPIO.SIAFI" = "CÓDIGO SIAFI"))
head(dat_with_ibge)
ls()
head(uf_map)
names(uf_map)
uf_map <- get_brmap("City")
names(uf_map)
uf_map$City
head(dat_with_ibge)
dat_with_ibge %>% group_by(`CÓDIGO IBGE`) %>% summarise(total = sum(VALOR.PARCELA))
dat_with_ibge %>% group_by(`CÓDIGO IBGE`) %>% summarise(total = sum(VALOR.PARCELA)) %>% inner_join(dat_with_ibge, c(`CÓDIGO IBGE` = "City"))
dat_with_ibge %>% group_by(`CÓDIGO IBGE`) %>% summarise(total = sum(VALOR.PARCELA)) %>% inner_join(dat_with_ibge, c(`CÓDIGO IBGE` = "City")) %>% ggplot() +geom_sf(aes(fill = total))
dat_with_ibge %>% group_by(`CÓDIGO IBGE`) %>% summarise(total = sum(VALOR.PARCELA)) %>% inner_join(dat_with_ibge, c("City" = `CÓDIGO IBGE`)) %>% ggplot() +geom_sf(aes(fill = total))
uf_map %>% inner_join(dat_with_ibge %>% group_by(`CÓDIGO IBGE`) %>% summarise(total = sum(VALOR.PARCELA)), c(`CÓDIGO IBGE` = "City")) %>% ggplot() +geom_sf(aes(fill = total))
uf_map %>% inner_join(dat_with_ibge %>% group_by(`CÓDIGO IBGE`) %>% summarise(total = sum(VALOR.PARCELA)), c("City" = `CÓDIGO IBGE`)) %>% ggplot() +geom_sf(aes(fill = total))
sum_ibge <- dat_with_ibge %>% group_by(`CÓDIGO IBGE`) %>% summarise(total = sum(VALOR.PARCELA))
sum_ibge
uf_map %>% inner_join(sum_ibge, by=c("City" = `CÓDIGO IBGE`))
uf_map %>% inner_join(sum_ibge, by=c("City" = "CÓDIGO IBGE"))
sum_ibge$`CÓDIGO IBGE` <- as.numeric(sum_ibge$`CÓDIGO IBGE`)
sum_ibge
uf_map %>% inner_join(sum_ibge, by=c("City" = "CÓDIGO IBGE"))
uf_map %>% inner_join(sum_ibge, by=c("City" = "CÓDIGO IBGE")) %>% ggplot() + geom_sf(aes(fill = total))
names(uf_map)
uf_map %>% inner_join(sum_ibge, by=c("City" = "CÓDIGO IBGE")) %>% ggplot() + geom_sf(aes(fill = total))
uf_map %>% inner_join(sum_ibge, by=c("City" = "CÓDIGO IBGE")) %>% ggplot() + geom_sf(aes(fill = total)) + scale_fill_viridis_c(option = 2) 
uf_map %>% inner_join(sum_ibge, by=c("City" = "CÓDIGO IBGE")) %>% ggplot() + geom_sf(aes(fill = total),colour = "black", size = 0.1) + scale_fill_viridis_c(option = 2) 
uf_map %>% inner_join(sum_ibge, by=c("City" = "CÓDIGO IBGE")) %>% ggplot() + geom_sf(aes(fill = log(total)),colour = "black", size = 0.1) + scale_fill_viridis_c(option = 2) 
uf_map %>% inner_join(sum_ibge, by=c("City" = "CÓDIGO IBGE")) %>% ggplot() + geom_sf(aes(fill = log(total)),colour = "black", size = 0.1) + scale_fill_viridis_c(option = 2) + theme(legend.text = "Log(valor)")
uf_map %>% inner_join(sum_ibge, by=c("City" = "CÓDIGO IBGE")) %>% ggplot() + geom_sf(aes(fill = log(total)),colour = "black", size = 0.1) + scale_fill_viridis_c(option = 2) + scale_fill_discrete(name = "Log(valor)")
uf_map %>% inner_join(sum_ibge, by=c("City" = "CÓDIGO IBGE")) %>% ggplot() + geom_sf(aes(fill = log(total)),colour = "black", size = 0.1) + scale_fill_viridis_c(option = 2) + scale_fill_continuous(name = "Log(valor)")
uf_map %>% inner_join(sum_ibge, by=c("City" = "CÓDIGO IBGE")) %>% ggplot() + geom_sf(aes(fill = log(total)),colour = "black", size = 0.1) + scale_fill_viridis_c(option = 2)
uf_map %>% inner_join(sum_ibge, by=c("City" = "CÓDIGO IBGE")) %>% ggplot() + geom_sf(aes(fill = log(total)),colour = "black", size = 0.1) + scale_fill_viridis_c(option = 2) + labs(fill = "Log(valor)") 
uf_map %>% inner_join(sum_ibge, by=c("City" = "CÓDIGO IBGE")) %>% ggplot() + geom_sf(aes(fill = log(total)),colour = "black", size = 0.1) + scale_fill_viridis_c(option = 2) + labs(fill = "Log(valor)", title = "Bolsa Família") 
savehistory("log.R")
